title: Grantwell Blog
description: Insights on public safety grant management, compliance, and funding automation.
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-seo-tag
defaults:
  - scope:
      path: ""
    values:
      layout: default
minima:
  skin: classic
  social_links:
    - { platform: website,     user_url: https://grantwell.co }
    - { platform: linkedin,    user_url: https://www.linkedin.com/company/grantwell }
markdown: kramdown
plugins:
  - jekyll-feed

